// vue-todo-app/src/components/TodoItem.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import { Todo } from '../types';
import { useTodosStore } from '../stores/todos';

const props = defineProps<{
  todo: Todo;
}>();

const emit = defineEmits(['updated']);

const todosStore = useTodosStore();

const isEditing = ref(false);
const editTitle = ref(props.todo.title);
const editDescription = ref(props.todo.description);
const loading = ref(false);

const localTodo = ref<Todo>({ ...props.todo });

watch(
  () => props.todo,
  (newTodo) => {
    localTodo.value = { ...newTodo };
    editTitle.value = newTodo.title;
    editDescription.value = newTodo.description;
  },
  { immediate: true, deep: true }
);

const statusClasses = computed(() => {
  return localTodo.value.completed === 1
    ? 'bg-success-500 text-white'
    : 'bg-warning-500 text-white';
});

const statusText = computed(() => {
  return localTodo.value.completed === 1 ? 'Completed' : 'Pending';
});

async function toggleStatus() {
  loading.value = true;
  try {
    await todosStore.toggleTodoStatus(localTodo.value.id);
    emit('updated');
  } finally {
    loading.value = false;
  }
}

async function deleteTodo() {
  if (!confirm('Are you sure you want to delete this todo?')) return;

  loading.value = true;
  try {
    await todosStore.deleteTodo(localTodo.value.id);
    emit('updated');
  } finally {
    loading.value = false;
  }
}

function startEdit() {
  editTitle.value = localTodo.value.title;
  editDescription.value = localTodo.value.description;
  isEditing.value = true;
}

async function saveEdit() {
  if (!editTitle.value.trim()) return;

  loading.value = true;
  try {
    await todosStore.updateTodo(localTodo.value.id, {
      title: editTitle.value,
      description: editDescription.value
    });

    localTodo.value.title = editTitle.value;
    localTodo.value.description = editDescription.value;

    isEditing.value = false;

    emit('updated');
  } finally {
    loading.value = false;
  }
}

function cancelEdit() {
  isEditing.value = false;
}
</script>

<template>
  <div
    class="todo-item card p-4 mb-4 relative overflow-hidden transition-all duration-300"
    :class="{ 'opacity-70': loading }"
  >
    <div
      v-if="loading"
      class="absolute inset-0 flex items-center justify-center bg-black bg-opacity-10 z-10"
    >
      <svg
        class="animate-spin h-5 w-5 text-primary-600"
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
      >
        <circle
          class="opacity-25"
          cx="12"
          cy="12"
          r="10"
          stroke="currentColor"
          stroke-width="4"
        ></circle>
        <path
          class="opacity-75"
          fill="currentColor"
          d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
        ></path>
      </svg>
    </div>

    <div v-if="!isEditing" class="flex flex-col md:flex-row md:items-center">
      <div class="flex-1">
        <div class="flex items-center mb-2">
          <span :class="statusClasses" class="text-xs font-medium px-2 py-1 rounded-full mr-2">
            {{ statusText }}
          </span>
          <h3 class="text-lg font-medium line-clamp-1">{{ localTodo.title }}</h3>
        </div>
        <p class="text-gray-600 dark:text-gray-300 mb-3 line-clamp-2">{{ localTodo.description }}</p>
      </div>
      <div class="flex space-x-2 md:ml-4">
        <button @click="toggleStatus" class="btn btn-secondary text-sm" :disabled="loading">
          {{ localTodo.completed === 1 ? 'Mark Incomplete' : 'Mark Complete' }}
        </button>
        <button @click="startEdit" class="btn btn-primary text-sm" :disabled="loading">
          Edit
        </button>
        <button @click="deleteTodo" class="btn btn-danger text-sm" :disabled="loading">
          Delete
        </button>
      </div>
    </div>

    <div v-else class="edit-form">
      <div class="mb-3">
        <label for="editTitle" class="form-label">Title</label>
        <input
          id="editTitle"
          v-model="editTitle"
          type="text"
          class="form-input"
          placeholder="Todo title"
        />
      </div>
      <div class="mb-4">
        <label for="editDescription" class="form-label">Description</label>
        <textarea
          id="editDescription"
          v-model="editDescription"
          class="form-input"
          rows="3"
          placeholder="Todo description"
        ></textarea>
      </div>
      <div class="flex justify-end space-x-2">
        <button @click="cancelEdit" class="btn btn-secondary" :disabled="loading">Cancel</button>
        <button @click="saveEdit" class="btn btn-primary" :disabled="loading">Save</button>
      </div>
    </div>
  </div>
</template>

// react-todo-app/src/components/todo/TodoItem.tsx
import React, { useState } from 'react';
import { Edit, Trash2, Check, X, Save } from 'lucide-react';
import { Todo } from '../../types';
import Button from '../ui/Button';

interface TodoItemProps {
  todo: Todo;
  onToggleComplete: (todo: Todo) => Promise<void>;
  onDelete: (id: number) => Promise<void>;
  onUpdate: (id: number, title: string, description: string) => Promise<void>;
}

const TodoItem: React.FC<TodoItemProps> = ({
  todo,
  onToggleComplete,
  onDelete,
  onUpdate,
}) => {
  const [isEditing, setIsEditing] = useState(false);
  const [editTitle, setEditTitle] = useState(todo.title);
  const [editDescription, setEditDescription] = useState(todo.description);
  const [isLoading, setIsLoading] = useState(false);

  const handleToggleComplete = async () => {
    if (isLoading) return;
    setIsLoading(true);
    try {
      await onToggleComplete(todo);
    } finally {
      setIsLoading(false);
    }
  };

  const handleDelete = async () => {
    if (isLoading) return;
    setIsLoading(true);
    try {
      await onDelete(todo.id);
    } finally {
      setIsLoading(false);
    }
  };

  const handleUpdate = async () => {
    if (isLoading || editTitle.trim() === '') return;
    
    setIsLoading(true);
    try {
      await onUpdate(todo.id, editTitle, editDescription);
      setIsEditing(false);
    } finally {
      setIsLoading(false);
    }
  };

  const handleCancel = () => {
    setEditTitle(todo.title);
    setEditDescription(todo.description);
    setIsEditing(false);
  };

  return (
    <div className={`
      bg-white dark:bg-gray-800 rounded-lg shadow-sm 
      border border-gray-200 dark:border-gray-700
      mb-3 p-4 animate-fade-in transition-all
      ${todo.completed ? 'opacity-70' : ''}
    `}>
      {isEditing ? (
        <div className="space-y-3">
          <input
            type="text"
            value={editTitle}
            onChange={(e) => setEditTitle(e.target.value)}
            className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm focus:ring-primary-500 focus:border-primary-500 bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
            placeholder="Title"
          />
          <textarea
            value={editDescription}
            onChange={(e) => setEditDescription(e.target.value)}
            className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-md shadow-sm focus:ring-primary-500 focus:border-primary-500 bg-white dark:bg-gray-700 text-gray-900 dark:text-white"
            placeholder="Description"
            rows={2}
          />
          <div className="flex justify-end space-x-2 mt-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handleCancel}
              disabled={isLoading}
            >
              <X size={16} className="mr-1" />
              Cancel
            </Button>
            <Button
              variant="primary"
              size="sm"
              onClick={handleUpdate}
              isLoading={isLoading}
            >
              <Save size={16} className="mr-1" />
              Save
            </Button>
          </div>
        </div>
      ) : (
        <div>
          <div className="flex items-start justify-between">
            <div className="flex items-start space-x-3">
              <button
                onClick={handleToggleComplete}
                disabled={isLoading}
                className={`
                  mt-1 flex-shrink-0 h-5 w-5 rounded border
                  ${todo.completed
                    ? 'bg-primary-500 border-primary-600 text-white flex items-center justify-center'
                    : 'border-gray-300 dark:border-gray-600'
                  }
                `}
                aria-label={todo.completed ? "Mark as incomplete" : "Mark as complete"}
              >
                {todo.completed ? <Check size={14} /> : null}
              </button>
              <div>
                <h3 className={`text-lg font-medium ${
                  todo.completed
                    ? 'text-gray-500 dark:text-gray-400 line-through'
                    : 'text-gray-900 dark:text-white'
                }`}>
                  {todo.title}
                </h3>
                <p className={`text-sm mt-1 ${
                  todo.completed
                    ? 'text-gray-400 dark:text-gray-500 line-through'
                    : 'text-gray-600 dark:text-gray-300'
                }`}>
                  {todo.description}
                </p>
              </div>
            </div>
            <div className="flex space-x-2">
              <button
                onClick={() => setIsEditing(true)}
                disabled={isLoading}
                className="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300"
                aria-label="Edit todo"
              >
                <Edit size={18} />
              </button>
              <button
                onClick={handleDelete}
                disabled={isLoading}
                className="text-error-500 hover:text-error-700 dark:text-error-400 dark:hover:text-error-300"
                aria-label="Delete todo"
              >
                <Trash2 size={18} />
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default TodoItem;
